### PR TITLE
Parser.parse now rejecting promise instead of throwing errors

### PR DESCRIPTION
**Pull request by joeljuca**

### CODE REVIEW

**Comment by joeljuca** [comment]
To keep the PR focused on solving the current issue I used the `Q` to make and return a promise from the method.

**Comment by joeljuca** [comment]
Gonna write a test for that

**Comment by joeljuca** [comment]
There's a test for that method already, but it was breaking. After a small tweak it's working again (I needed to propagate the `http.read` errors to the exported promise).

**Comment by joeljuca** [comment]
@sergiovilar ready to rock 🤘

**Comment by sergiopvilar** [comment]
@joelwallis You didn't touched the tests but they are passing, it seems that we have a false positive here.

**Comment by sergiopvilar** [comment]
@joelwallis I did some tests locally with this branch and for sure we can't solve this false positive without Bluebird. I'm closing here in favor of #8.

**Pull request closed without merging**
